/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_tercer_trimestre;

/**
 *
 * @author artur
 */
public class TarjetaDeCredito extends javax.swing.JFrame {

    /**
     * Creates new form TarjetaDeCredito
     */
    public TarjetaDeCredito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TipoTarjetaText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ExpiraText = new javax.swing.JLabel();
        TitularTarjetaText = new javax.swing.JLabel();
        ControlCodeText = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        Pagar = new javax.swing.JButton();
        Guardar = new javax.swing.JCheckBox();
        NumeroTarjeta = new javax.swing.JTextField();
        TitularTarjeta = new javax.swing.JTextField();
        ControlCode = new javax.swing.JTextField();
        TipoTarjetaCombo = new javax.swing.JComboBox<>();
        Data1 = new javax.swing.JComboBox<>();
        Data2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TipoTarjetaText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TipoTarjetaText.setForeground(new java.awt.Color(240, 240, 240));
        TipoTarjetaText.setText("Tipo de Tarjeta");
        jPanel1.add(TipoTarjetaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 120, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Número de la tarjeta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        ExpiraText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExpiraText.setForeground(new java.awt.Color(240, 240, 240));
        ExpiraText.setText("Expira");
        jPanel1.add(ExpiraText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 20));

        TitularTarjetaText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TitularTarjetaText.setForeground(new java.awt.Color(240, 240, 240));
        TitularTarjetaText.setText("Nombre del titular de la tarjeta");
        jPanel1.add(TitularTarjetaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        ControlCodeText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ControlCodeText.setForeground(new java.awt.Color(240, 240, 240));
        ControlCodeText.setText("Código de control");
        jPanel1.add(ControlCodeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        Atras.setText("Atrás");
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 80, 30));

        Pagar.setText("Pagar");
        jPanel1.add(Pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 80, 30));

        Guardar.setText("Guardar esta tarjeta de crédito para usos futuros");
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        NumeroTarjeta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(NumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 160, 30));

        TitularTarjeta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(TitularTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 130, 30));
        jPanel1.add(ControlCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 70, 30));

        TipoTarjetaCombo.setBackground(new java.awt.Color(51, 51, 51));
        TipoTarjetaCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TipoTarjetaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visa", "Mastercard", "American Express" }));
        jPanel1.add(TipoTarjetaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 170, 30));

        Data1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Data1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(Data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 50, 30));

        Data2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Data2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041" }));
        jPanel1.add(Data2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarjetaDeCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarjetaDeCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarjetaDeCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarjetaDeCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarjetaDeCredito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JTextField ControlCode;
    private javax.swing.JLabel ControlCodeText;
    private javax.swing.JComboBox<String> Data1;
    private javax.swing.JComboBox<String> Data2;
    private javax.swing.JLabel ExpiraText;
    private javax.swing.JCheckBox Guardar;
    private javax.swing.JTextField NumeroTarjeta;
    private javax.swing.JButton Pagar;
    private javax.swing.JComboBox<String> TipoTarjetaCombo;
    private javax.swing.JLabel TipoTarjetaText;
    private javax.swing.JTextField TitularTarjeta;
    private javax.swing.JLabel TitularTarjetaText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
